# Generated by Django 4.2.7 on 2023-11-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='creator',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
