# Generated by Django 4.2.7 on 2023-11-07 10:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_blog_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddField(
            model_name='blog',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
